//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolSalimgareeva
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.ProductMaterial = new HashSet<ProductMaterial>();
        }
    
        public int MaterialID { get; set; }
        public int MaterialType { get; set; }
        public string MaterialName { get; set; }
        public int MaterialQuantityinPack { get; set; }
        public int MaterialUnitID { get; set; }
        public string MaterialDescription { get; set; }
        public string MaterialImage { get; set; }
        public decimal MaterialCost { get; set; }
        public int MaterialQuantityInStock { get; set; }
        public int MaterialMinimumQuantity { get; set; }
    
        public virtual MaterialType MaterialType1 { get; set; }
        public virtual MaterialUnits MaterialUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
    }
}
