//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolSalimgareeva
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int PartnerID { get; set; }
        public int PartnerTypeID { get; set; }
        public string PartnerCompanyName { get; set; }
        public string PartnerDirectorFullname { get; set; }
        public string PartnerEmail { get; set; }
        public string PartnerPhoneNumber { get; set; }
        public string PartnerLegalAddress { get; set; }
        public string PartnerINN { get; set; }
        public int PartnerRating { get; set; }
        public string PartnerLogo { get; set; }

        public int PartnerDiscount
        {
            get
            {
                int ProductsCount = 0;
                foreach (var orders in SalimgareevaMasterPolEntities.GetContext().Orders.Where(o => o.PartnerID == this.PartnerID).ToList())
                {
                    ProductsCount += orders.OrderProductQuantity;
                }

                if (ProductsCount < 10000)
                    return 0;
                if (ProductsCount < 50000)
                    return 5;
                if (ProductsCount < 300000)
                    return 10;
                return 15;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual PartnerType PartnerType { get; set; }
    }
}
