//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolSalimgareeva
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int PartnerID { get; set; }
        public int PartnerTypeID { get; set; }
        public string PartnerCompanyName { get; set; }
        public string PartnerDirectorFullname { get; set; }
        public string PartnerEmail { get; set; }
        public string PartnerPhoneNumber { get; set; }
        public string PartnerLegalAddress { get; set; }
        public string PartnerINN { get; set; }
        public int PartnerRating { get; set; }
        public string PartnerLogo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual PartnerType PartnerType { get; set; }
    }
}
