//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPolSalimgareeva
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Orders = new HashSet<Orders>();
            this.ProductMaterial = new HashSet<ProductMaterial>();
        }
    
        public string ProductArticul { get; set; }
        public int ProductTypeID { get; set; }
        public string ProductName { get; set; }
        public decimal ProductMinimalCostForPartner { get; set; }
        public string ProductDescription { get; set; }
        public string ProductImage { get; set; }
        public decimal ProductPackageLength { get; set; }
        public decimal ProductPackageWidth { get; set; }
        public decimal ProductPackageHeight { get; set; }
        public decimal ProductNetWeight { get; set; }
        public decimal ProductWeight { get; set; }
        public string ProductCertificate { get; set; }
        public string ProductStandartNumber { get; set; }
        public System.TimeSpan ProductProductionTime { get; set; }
        public decimal ProductPrimeCost { get; set; }
        public int ProductManufactoryNumber { get; set; }
        public int ProductWorkersOnFactoryCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
